language: python
python:
  - "2.7"
cache: pip
install:
  - pip install pillow pyqrcode pypng pyinstaller web.py pycrypto simple-crypt win_inet_pton PySocks
script: 
  - pyinstaller --uac-admin --onefile --noconsole --log-level=INFO gui.py --icon=graphics\icon.ico
  - pyinstaller --uac-admin --onefile --log-level=INFO node.py --icon=graphics\icon.ico
  - pyinstaller --uac-admin --onefile --log-level=INFO miner.py --icon=graphics\icon.ico
  - pyinstaller --uac-admin --onefile --log-level=INFO ledger_explorer.py --icon=graphics\icon.ico --hidden-import=ledger_explorer
notifications:
  slack: cryptobismuth:Mtd8QY1ElBCfM7ijzsyCE7HU
  email: false
